### ISSUE TITLE
[v1.0.0b] [Task] - Improve Recipe Printing

### ISSUE THREAD

**Issue by hay-kot** [mealie-recipes/mealie#1082]
### What is the problem this task addresses?

Printing a Recipe in mealie is half-baked at best. Some information is unavailable, and the formatting can be inconsistent. 

### Proposed/Possible Solution(s)?

Mealie should implementing a customizable printing page similar to King Arthur's implementation 

See here (click print):

- https://www.kingarthurbaking.com/recipes/irish-whiskey-cheesecake-recipe

**Comment by tbleiker** [comment]
When I chose print, I get:
- Comments at the top (I would put this rather at the end - if at all...)
- Left third of the page is blank (if side menu is not closed)
- Empty ingredient list (except for the notes)
- No section in the ingredient list (just all the ingredients after one another without the section title)

I tested with Firefox and Chrome on Linux. Server: Docker on Linux, most current frontend-nigthly (da57184c5690) and api-nightly (4ed3545a8de7) with sqlite.

**Comment by hay-kot** [comment]
> When I chose print, I get:
> 
> * Comments at the top (I would put this rather at the end - if at all...)
> * Left third of the page is blank (if side menu is not closed)
> * Empty ingredient list (except for the notes)
> * No section in the ingredient list (just all the ingredients after one another without the section title)
> 
> I tested with Firefox and Chrome on Linux. Server: Docker on Linux, most current frontend-nigthly (da57184c5690) and api-nightly (4ed3545a8de7) with sqlite.

I think all of these things are more or less addressed in the most recent nightly version

**Comment by tbleiker** [comment]
Looks a lot better now!

Last point is still a problem
- No section in the ingredient list (just all the ingredients after one another without the section title)

**Comment by michael-genson** [comment]
I submitted a PR for this: [Fixed text color on RecipeCard in RecipePrintView and implemented ingredient sections](https://github.com/hay-kot/mealie/pull/1351)
