### ISSUE TITLE
[v1.0.0b] - SMTP authentication with Gmail fails

### ISSUE THREAD

**Issue by CodingKoopa** [mealie-recipes/mealie#1568]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

When I send a test email from the Mealie interface, the following errors occur:

```
mealie-api         | INFO: 15-Aug-22 19:37:36   send email result: <emails.backend.SMTPResponse status_code=None status_text=None>
mealie-api         | ERROR: 15-Aug-22 19:37:36  send email error: [Errno None] SMTP AUTH extension not supported by server.: None
mealie-api         | 172.19.0.7:32938 - "POST /api/admin/email HTTP/1.1" 200
```

I have the Mealie SMTP credentials configured to use:

- The Gmail SMTP server.
- TLS encryption.
- The part before the Gmail `@` as the username.
- An [app password](https://support.google.com/accounts/answer/185833) associated with the Google account account as the password.

I am able to send mail using the same credentials but with [msmtp](https://marlam.de/msmtp/), so they should be correct. Configuration files are privately available by request.

### Deployment

Docker (Linux)

### Deployment Details

I am using nginx as a reverse proxy. None of the Mealie ports are exposed outside of the Docker network.

**Comment by FonduemangVI** [comment]
I am also experiencing the same issue trying to use Exchangel online. I get the same as above

**Comment by hay-kot** [comment]
Could one of your try your configuration with that latest nightly once it's built (about an hour)  and see if the issue persists?

**Comment by FonduemangVI** [comment]
![image](https://user-images.githubusercontent.com/15520607/197332894-07a20ad9-0c86-4aed-94aa-230f7f736c5e.png)
The server is now crashing with the above error. This is the API container

**Comment by hay-kot** [comment]
:( 

This build should fix it https://github.com/hay-kot/mealie/actions/runs/3304314453

**Comment by FonduemangVI** [comment]
![image](https://user-images.githubusercontent.com/15520607/197385550-490c6340-0d0b-4330-9659-ececde0895ad.png)
Okay so server is running again however still getting the same error when testing an email

**Comment by hay-kot** [comment]
I just set this up with my gmail account, I'm now pretty sure this isn't an issue with Mealie. Here are the settings that worked for me for gmail

```env
SMTP_HOST="smtp.gmail.com"
SMTP_PORT="465"
SMTP_FROM_NAME="myemail@gmail.com"
SMTP_FROM_EMAIL="myemail@gmail.com"
SMTP_AUTH_STRATEGY="SSL"
SMTP_USER="myemail@gmail.com"
SMTP_PASSWORD="YOUR_APP_PASSCODE"
```

You can't use your gmail password, you have to generate an App Password in the google dashboard. 

---

For outlook, I haven't been able to get it to work, but I don't think it's a problem with Mealie. From what I can tell outlook only supports TLS so with the following settings, I get a `Authentication unsuccessful, the user credentials were incorrect` error in the logs. I haven't been able to figure out how to authenticate correctly.

```env
SMTP_HOST="smtp.office365.com"
SMTP_PORT="587"
SMTP_FROM_NAME="myemail@outlook.com"
SMTP_FROM_EMAIL="myemail@outlook.com"
SMTP_AUTH_STRATEGY="TLS"
SMTP_USER="myemail@outlook.com"
SMTP_PASSWORD="MY_ACCOUNT_PASSOWRD"
```

**Comment by FonduemangVI** [comment]
Right okay. In my case I am pointing it to an Exchange Online instance that doesn't use, Username and PW auth as it's an SMTP relay that allows my public IP.

Which auth strategies are supported?

**Comment by Zackptg5** [comment]
I got gmail with 587/tls to work. However, I had to remove all of the quotes from the SMTP variables in my docker-compose file or I'd get name/server not found errors

**Comment by Opethel** [comment]
For what it is worth, I was able to get outlook (Office 365) to work with the below configuration. The key seemed to be that the default SMTP_FROM_NAME had to be changed to match myemail. 

```
SMTP_HOST="smtp.office365.com"
SMTP_PORT="587"
SMTP_FROM_NAME="myemail@outlook.com"
SMTP_FROM_EMAIL="myemail@outlook.com"
SMTP_AUTH_STRATEGY="TLS"
SMTP_USER="myemail@outlook.com"
SMTP_PASSWORD="APP Password"
```

**Comment by Christoph-87** [comment]
The above worked for me. But I had a % and $ in my password and there seemed to be issues with the escaping? After changing the password and removing those special characters (both at once), it worked.

**Comment by JuliusLedoux** [comment]
I don't know if this matters today, but I got it to work using the App Password option. Thank you!
