### ISSUE TITLE
[v1.0.0b] - 'Keep Screen Awake' doesn't work for iOS PWA

### ISSUE THREAD

**Issue by ghuser238490** [mealie-recipes/mealie#2305]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

On iOS 16.4 (iPhone 12) the switch "Keep Screen Awake" on the recipe pages doesn't prevent the device from turning the display off.

### Deployment

Docker (Linux)

### Deployment Details

Version
nightly
Build
[027fcbdcef743ff2767782f34fff7593ab32f1cf](https://github.com/hay-kot/mealie/commit/027fcbdcef743ff2767782f34fff7593ab32f1cf)

**Comment by hay-kot** [comment]
Can you go here

https://vueuse.org/core/useWakeLock/#usewakelock

And tell me what these say? 

<img width="743" alt="CleanShot 2023-03-31 at 14 51 37@2x" src="https://user-images.githubusercontent.com/64056131/229246264-1de25c45-b001-4156-9741-b1a915a0a5e7.png">

It looks like it's unsupported on your browser, but I'm not sure why it is even an option then. I see the same thing on my IPad. 

https://developer.mozilla.org/en-US/docs/Web/API/Screen_Wake_Lock_API#browser_compatibility

**Comment by ghuser238490** [comment]
Hi @hay-kot, thanks for looking into this!

Output on https://vueuse.org/core/useWakeLock/#usewakelock in iOS Safari and macOS Safari 16.4 is the same as in your screenshot above: 
```
Is Supported: true
Is Active: false
``` 
I did some tests:
- iOS Safari: It's working (screen stays active)
- iOS PWA on homescreen: It's not working, screen locks after the declared time in the iOS settings (PWA was reinstalled before)
- macOS Chrome (ver. 111.0) PWA: It's working (screen stays active)
- macOS Safari 16.4: It's working (screen stays active)

**Comment by brent20** [comment]
I can confirm this also does not work for me when I'm using Mealie added to my homescreen as a web app. 
Latest iOS, iPhone 14 Pro.

**Comment by boc-the-git** [comment]
@brent20 just confirming you're running a recent version of Mealie, as it relates to your recent comment? 
Can you please go to https://yourmealieurl/admin/site-settings, hit "Bug Report" and send us that info?
Can you please also test deleting the "re-installing" the PWA on your phone, just to rule out any issues there.

**Comment by cmintey** [comment]
I'll also add my hat into the ring here. Just tested with a recent nightly on the latest iOS. The screen stays awake when using the Safari browser, but does not work when the PWA is installed. I did a "reinstall" of the PWA and it still didn't work.

```
**Details**
Version: nightly
Build: b28aa828469f898b936337b679cbfdf75fa7ffad
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.52.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: Yes
Email Configured: Yes
Docker Volume: success
```

**Comment by brent20** [comment]
Hey there, sorry for the delay, but yes, it was still not working - thank you @cmintey for also confirming.
I just updated my docker containers recently and it is still not working as expected. Here’s my Bug Report details as requested:


**Details**
Version: nightly
Build: 46cb36212a7dfbfbe051fed1782dba1fdcc00b9b
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: postgres
Recipe Scraper Version: 14.53.0

**Checks**
Secure Site: Yes
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No

**Comment by jebabin** [comment]
This is an IOS bug. The bug is described here https://bugs.webkit.org/show_bug.cgi?id=205104 and is fixed in WebKit but not yet in Safari/IOS
An alternative is to use a JavaScript lib like NoSleep (https://github.com/richtr/NoSleep.js/). It use alternative like playing a background empty audio file to prevent screen going in sleep mode when the WakeLock api is not supported
As recent IOS version report to support the API but it’s broken in WPA mode, a patch is needed to still use the sound trick on IOS 16.4+
See https://github.com/richtr/NoSleep.js/issues/156

**Comment by ChipSkylark37** [comment]
Just throwing in a quick comment that this is still broken on iOS 17.6.1 using the 'Add to Homescreen' feature.

Is there any idea of a timeline to fix this? Is this just an iOS Bug and there's no control over it? As its been an issue since 2023 without any real resolution.

**Comment by boc-the-git** [comment]
> Is there any idea of a timeline to fix this? Is this just an iOS Bug and there's no control over it? As its been an issue since 2023 without any real resolution.

Yes @ChipSkylark37, this is iOS specific. Feature works great on Android.
I went down a rabbit hole about 3 weeks ago based on @jebabin's comment, looking to see if there was a good solution for iOS.. I can't recall my specific findings other than it being a lot of trouble and maybe not possible.
I'm not sure if there might be hacky solutions that could work; I had already invested too much time in it.

**Comment by ChipSkylark37** [comment]
I wonder if a native iOS app wouldn't have that limitation. I'm sure that would be no simple task to attempt, even with TestFlight. 

Anyways, good to at least get confirmation - I thought I was going crazy with it not keeping the screen on

Cheers.

**Comment by hay-kot** [comment]
Going to close this issue since it's an underlying issue with iOS and webkit and not something we can resolve directly.

I will say that I haven't seen this issue in the latest iOS so maybe they've fixed it?

**Comment by JonathanPitre** [comment]
I can test and report back but yes this is an iOS issue

**Comment by ChipSkylark37** [comment]
I am on the latest public 18.1.1 iOS release and this is still an issue if using PWA. 

If I use the shortcut 'Sent to Homescreen' the screen does not stay on. 

When just using Safari going to my mealie instance, 'Keep Screen Awake' works fine. 

Is there a possibility to add in something like a background / playing video / audio in some sense that was linked previously:
https://github.com/mealie-recipes/mealie/issues/2305#issuecomment-1885639745

Thinking of a way to trick the system into keeping the screen active using the PWA to bypass whatever odd limitation iOS has that doesn't appear to be any priority to implement into iOS Safari.

**Comment by cmintey** [comment]
FYI this is _finally_ fixed in iOS 18.4!

https://developer.apple.com/documentation/safari-release-notes/safari-18_4-release-notes#Home-Screen-Web-Apps

**Comment by boc-the-git** [comment]
> FYI this is _finally_ fixed in iOS 18.4!
> 
> https://developer.apple.com/documentation/safari-release-notes/safari-18_4-release-notes#Home-Screen-Web-Apps

That's pretty big news!
Have you had a chance to test it @cmintey and confirm it _actually_ fixes the issue like we'd hope?

I'm on Android so it's not directly relevant to me 🙈

**Comment by ghuser238490** [comment]
@boc-the-git I can confirm it's working on iOS 18.4 and it looks like the issue is fixed eventually.

**Comment by cmintey** [comment]
Yep, I tested it before posting!
