### ISSUE TITLE
[BUG] - Recipie Parser can't handle prices

### ISSUE THREAD

**Issue by GameDungeon** [mealie-recipes/mealie#5422]
### First Check

- [x] This is not a feature request.
- [x] I added a very descriptive title to this issue (title field is above this).
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Some of the websites I use append price data in their ingredients lists and the recipe parsers can't handle that, when it really should be parsed to notes.

> 2 Tbsp cooking oil* ($0.10) 
> 1/4 tsp cayenne pepper ($0.02)

Side note, they also can't handle the asterisk some sites add when they have a note on an ingredient. It should be possible to filter that out of the ingredient name.  

### Steps to Reproduce

Import recipe with priced ingredients

### Please provide relevant logs

N/A

### Mealie Version

v2.8.0 

### Deployment

Other (please specify below)

### Additional Deployment Details

Nix

**Comment by aliyyanWijaya** [comment]
Hello, I would like to contribute to fix this issue, may I allow to start working on it?

**Comment by GameDungeon** [comment]
This is an open source project, anyone is free to contribute :)

I see no sign that anyone else is working on it, so you contributing would be great.

**Comment by aliyyanWijaya** [comment]
Thank you, I am going to start working on this.

**Comment by mariodz95** [comment]
It seems to me this is already fixed. Is there any specific URL that cannot be parsed?

**Comment by GameDungeon** [comment]
Nope, I see the same issue still. Pretty much any recipe on https://www.budgetbytes.com/ exhibits this behavior due to how the format the recipes. It thinks that cayenne pepper ($0.02) is a different ingredient than cayenne pepper.

**Comment by jeromer-dev** [comment]
Hi! I tested several recipes from https://www.budgetbytes.com and didn’t run into this issue.
Maybe it’s already been fixed?

**Comment by GameDungeon** [comment]
It appears to work now if the ingredients exists, but it wants to create a new ingredient with the cost in it if it doesn't.

**Comment by henry1113nz** [comment]
I had a look at this and wanted to post what I found, since two people above
could not reproduce it.

**The price part no longer reproduces.** Both parsers handle it:

    NLP     "1/4 tsp cayenne pepper ($0.02)"  ->  0.25 / teaspoon / "cayenne pepper"
    Brute   "1/4 tsp cayenne pepper ($0.02)"  ->  0.25 / tsp      / "cayenne pepper", note "$0.02"

**The asterisk part is still there, and only in the brute parser:**

    Brute   "2 Tbsp cooking oil*"        ->  2 / Tbsp / "cooking oil*"     <-- marker kept
    Brute   "1 cup all-purpose flour**"  ->  1 / cup  / "all-purpose flour**"
    Brute   "1 cup milk"                 ->  1 / cup  / "milk"             (control, fine)
    NLP     "2 Tbsp cooking oil*"        ->  2 / Tbsp / "cooking oil"      (handled)

The brute parser joins the remaining tokens into the food name with no cleanup
step, so any punctuation that is there stays.

One note on the impact, because it is smaller than it looks: this does not create
duplicate foods. `IngredientFoodModel.normalize()` strips the asterisk, so
`cooking oil*` and `cooking oil` normalise to the same string and match at 100.
The actual problem is that when the food does not already exist yet, the new
record is created from the un-normalised name, so the user ends up with a food
permanently named `cooking oil*`.

I'd like to work on this if nobody else is. My plan is to strip trailing asterisks
from the parsed food name in the brute parser, with a unit test added to
`test_brute_parser.py`.

<img width="2829" height="1529" alt="Image" src="https://github.com/user-attachments/assets/28f41f39-2a86-43a1-acfb-590a0b7b7d31" />

<img width="2822" height="1518" alt="Image" src="https://github.com/user-attachments/assets/31ee09e2-0812-49f3-8b19-4ec773c7a8f0" />

<img width="2814" height="1513" alt="Image" src="https://github.com/user-attachments/assets/b0e94409-0b7a-459b-9dc2-00b011b26a11" />
