### ISSUE TITLE
[BUG] - 'I Made This'-Calender chooses wrong Date

### ISSUE THREAD

**Issue by shoneg** [mealie-recipes/mealie#5818]
### First Check

- [x] This is not a feature request.
- [x] I added a very descriptive title to this issue (title field is above this).
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the Mealie documentation, with the integrated search.
- [x] I already read the docs and didn't find an answer.
- [x] This issue can be replicated on the demo site (https://demo.mealie.io/).

### What is the issue you are experiencing?

Choosing a date on the calender of 'I Made This', selected the day before the selected one.

### Steps to Reproduce

1) I navigate to a reciept and click on the the 'I Made This'-Button (hope I've translated it correctly, because it's in German for me)
2)  I click on the date and a calendar appears
3) I choose any date (e.g. 2025-07-17)
4) I the date field shows the day before the day I've selected (e.g. 2025-07-16)
optionl:
5) I click on the date filed again and the originally selected day (e.g. 2025-07-17) is shown as selected

### Please provide relevant logs

No relevent logs here

### Mealie Version

3.0.1 on my side and 3.0.2 on demo page

### Deployment

Docker (Linux)

**Comment by michael-genson** [comment]
This should be fixed in nightly: https://github.com/mealie-recipes/mealie/pull/5798

Can you double check the demo site and see if you can reproduce? And, if you can, what timezone are you in, and what local time are you trying at?

**Comment by shoneg** [comment]
I've double checked it now and I can still reproduce it. I'm in timezone Europe/Berlin. This is a screenshot of [this page](https://demo.mealie.io/g/home/r/salted-caramel-brownies) a few minutes ago (20:06:59 - local German time):

![Image](https://github.com/user-attachments/assets/1508a400-0d51-4cf8-8c34-bca1ae3022ad)

**Comment by michael-genson** [comment]
Thank you! I'll have to double check what's going on here because I definitely tested this in my PR and it worked fine. Surely something timezone related

**Comment by michael-genson** [comment]
I just realized I was thinking about this meal plan PR: https://github.com/mealie-recipes/mealie/pull/5748
Similar issue, but a different component. This one wasn't addressed at all (which is surely why it's still broken ;) )

**Comment by lehnerpat** [comment]
I've submitted a fix for this in https://github.com/mealie-recipes/mealie/pull/6079 :)

**Comment by lehnerpat** [comment]
@shoneg The fix has been merged 🎉  if you could test it (locally or in the nightly demo) to make sure it also works for you now, that would be great! ☺️

**Comment by shoneg** [comment]
Nice thanks 🎉
